#! /usr/bin/python

import sys
import re

pat = re.compile('(.*)(<\d+>)')
bus_name = ''
bus_found = False
newline = []
newlines = []

with open(sys.argv[1], 'r') as f:
    lines = f.readlines()
    for line in lines:
        if line.startswith('.subckt'):
            for port in line.split():
                rematch = pat.match(port)
                if(rematch): # bus pin
                    bus_found = True
                    if(bus_name == rematch.group(1)): # continue match
                        rlist.append(port)
                    else: # new group
                        rlist = [port]
                        bus_name = rematch.group(1)
                else:
                    if(bus_found):
                        newline = newline+list(reversed(rlist))
                        bus_found = False
                    newline.append(port)
            if(bus_found):
                newline = newline+list(reversed(rlist))
            newlines.append(' '.join(newline)+'\n')
        else:
            newlines.append(line)

with open(sys.argv[1], 'w') as f:
    #f.writelines('\n'.join(newlines)+'\n')
    f.writelines(newlines)
